### PR TITLE
Added chart gimmick documentation

### PR DESCRIPTION
**Pull request by nexeh**
Once the new chart gimmick is merged this will be the documentation for it. You are welcome to change it. I know im not the best writer in the world! Remember that this new gimmick need to be brought into the gh-pages for this documentation example to run!

### CODE REVIEW

**Comment by nexeh** [comment]
This is also for issue #157

**Comment by nexeh** [comment]
So this documentation is live now but the example wont render because the new gimmick isnt merged in yet.

**Comment by Dynalon** [comment]
I've removed the documentation again in commit d97e2079ad2d56b4e2d5d773e0925f86d2dd6115 because it is not working (I tried locally with latest mdwiki build that has the chart gimmick in it).

The problem is with chart.js. I spend an hour debugging it, and it seems it has race conditions in it. I get a null reference error because "this.scale" is undefined when trying to access it. During debugging I found that this is called before buildScale (which would initialize the scale). I don't know why this happens, seems to me like a bug in chart.js

**Comment by nexeh** [comment]
@Dynalon , I will debug it. I already have some ideas. Now that you merged the Gimmick into the documentation it should be easy.

**Comment by nexeh** [comment]
@Dynalon I got to the root of the problem. I knew when i saw the ' "this.scale" is undefined ' that this was a chart configuration problem. I generate the chart config so i knew it had to be some issue with my logic. What i found is that my documentation is more true than i even knew...

Note: Currently only support a single table on a page. You CAN have multiple charts from the same table.

Well the alert section has a table in it and results in the table being parsed and the chart config doesn't describe a chart that could be rendered. So my first idea was to move the chart above the alert and that doesn't fully resolve the issue. If i remove the table from the page everything works fine. SO... my documentation is very correct.... 

This is a restriction i am willing to live with. One of your guidelines for MDWiki is not to modify MD. Unless each table had a predictable id or class i couldn't target a single table. 

Short term fix could be to remove the other table in the gimmick documentation

**Comment by Dynalon** [comment]
Well, that is a problem but I think this can be fixed. In the gimmick, you got the $link element which represents the link created by the `[gimmick:chart]` entry. Using jQuery traversing, we could agree on using the tables that is *closest* to the this $link element. Without testing, something like `var $table = $link.parents().find("table").last()` should do the trick and select the right table. You would then need to assemble the configuration from the `$table` element.

It would also be nice if there was some kind of check, i.e. if no table could be found or the configuration is faulty so that you don't try to create the chart.

**Comment by nexeh** [comment]
@Dynalon Resolved in pull request #209 . We can move the discussion there.

**Pull request merged**
