### PR TITLE
Add emoji gimmick.

### PR DESCRIPTION
**Pull request by guillermocalvo**
# Emoji Gimmick

Enables [GitHub-like emojis](https://github.com/blog/1289-emoji-autocomplete).

There are upwards of [800 emojis available](http://www.emoji-cheat-sheet.com/).

The emoji are hosted on Heroku with a [Cloudflare CDN](http://www.tortue.me/).

## Usage

    :smile:

    :confused:

    :octocat:

### CODE REVIEW

**Comment by geekdave** [comment]
@Dynalon We'd be interested in this feature as well, as we make use of emoji like :white_check_mark: and :x: in our docs.  Are you open to this PR?  The build failure looks like some spurious npm install failure.

**Comment by Dynalon** [comment]
I don't like that it has a custom license header, stating it is LGPL licensed. MDwiki 0.6.x branch is strict GPL. Additionally, MDwiki requires a CLA to be signed (which the author has IIRC) so that I can relicense the code. As all code in the MDwiki repo should be under the same license, please remove the custom license header (you can retain you Copyright note + credit).

**Comment by guillermocalvo** [comment]
Done. Sorry about that @Dynalon.

**Comment by Dynalon** [comment]
Thx!

**Pull request merged**
