### PR TITLE
Fix navbar template

### PR DESCRIPTION
**Pull request by fritz-c**
- Fixed the template syntax to match that of Hogan's, which uses `#` and `/` in place of `if` and `/if`.
- Removed unnecessary semicolon.

### CODE REVIEW

**Comment by Dynalon** [comment]
Hi,

thanks for you work! Please fill out the CLA so I can accept this pull request (see http://dynalon.github.io/mdwiki/#!contribute/index.md#Steps_for_becoming_a_contributor).

**Comment by fritz-c** [comment]
I've submitted the CLA now.

Even after fixing this part, though, the navigation menu appears to be broken.
Given a `navigation.md` file with the following contents:
```
# Foo

[Bar1]()

  * # Bar2
  * [Bar3](Bar3.md)
  * [Bar4](Bar4.md)

[Bar5]()

  * # Bar6
  * [Bar7](Bar7.md)
  * [Bar8](Bar8.md)
  - - - -
  * # Bar9
  * [Bar10](Bar10.md)
```
The output appears as follows. 
navbar

Can you reproduce this?

**Comment by Dynalon** [comment]
Well, the `master` branch is heavily broken and a rewrite of lots of things. The 0.6.2 branch holds all the code used for mdwiki.info and all other previous releases. So yes, there is a ton of things not working in the `master` branch as they should

**Comment by Dynalon** [comment]
This is already fixed in `master`, closing this.

**Pull request closed without merging**
