### PR TITLE
Updated master Core

### PR DESCRIPTION
**Pull request by ComradeNixco**
many updates to core systems

### CODE REVIEW

**Comment by Dynalon** [comment]
Wow, many changes, thanks for your effort. I will take a closer look tomorrow.

**Comment by Dynalon** [comment]
It seems pako_deflate.min.js is missing in extlib. What is its use anyway? I would rather on HTTP gzip/brotli support than to include manual unzipping in MDwiki.

**Comment by Dynalon** [comment]
The rename from `$.initMDwiki` to `$.md.initMDwiki` must also be done in main.js file. Besides that (and the pako deflate which I removed from the build) your PR is okay. I can fix the necessary changes and merge it.

Before mergin I need you to submit the CLA, see for details: http://dynalon.github.io/mdwiki/#!contribute/cla-individual.md

**Comment by ComradeNixco** [comment]
Ok I'll see to it as soon as possible

**Comment by ComradeNixco** [comment]
pako is used to zip and unzip the content for the plantuml gimmick that is present in my other pull request (#344)

**Comment by ComradeNixco** [comment]
Also I filled the CLA

**Pull request closed without merging**
